package com.orders.customer.service.impl;

import com.orders.common.exception.CustomerNotFoundException;
import com.orders.common.exception.DuplicateCustomerException;
import com.orders.customer.dto.CustomerRequest;
import com.orders.customer.dto.CustomerResponse;

import com.orders.customer.model.Customer;
import com.orders.customer.repository.CustomerRepository;
import com.orders.customer.service.CustomerService;

import lombok.RequiredArgsConstructor;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

@Service
@Transactional(readOnly = true)
@RequiredArgsConstructor
public class CustomerServiceImpl implements CustomerService {

    private final CustomerRepository customerRepository;
    private final JdbcTemplate jdbcTemplate;

    // =========================================================
    // // CREATE
    // // =========================================================
    @Override
    @Transactional
    public CustomerResponse createCustomer(CustomerRequest request) {
        
        validateUniqueCustomer(request.getEmail());
        Customer customer = new Customer();
        customer.setCustomerNumber(generateCustomerNumber());
        mapRequestToEntity(request, customer);
        Customer savedCustomer = customerRepository.save(customer);
        return mapToResponse(savedCustomer);
    }

    // =========================================================
    // GENERATE CUSTOMER NUMBER
    // =========================================================
    private String generateCustomerNumber() {
        Long sequenceValue = jdbcTemplate.queryForObject("SELECT nextval('customer_number_seq')", Long.class);
        if (sequenceValue == null) {
            throw new IllegalStateException("Unable to generate customer number");
        }
        return String.format("CUS-%06d", sequenceValue);
    }

    // =========================================================
    // GET BY ID
    // =========================================================
    @Override
    public CustomerResponse getCustomerById(UUID id) {
        Customer customer = customerRepository.findById(id)
                .orElseThrow(() -> new CustomerNotFoundException(id));
        return mapToResponse(customer);
    }

    // =========================================================
    // GET BY CUSTOMER NUMBER
    // =========================================================
    @Override
    public CustomerResponse getCustomerByCustomerNumber(String customerNumber) {
        Customer customer = customerRepository.findByCustomerNumber(customerNumber)
                .orElseThrow(() -> new CustomerNotFoundException(customerNumber));
        return mapToResponse(customer);
    }

    // =========================================================
    // GET BY EMAIL
    // =========================================================
    @Override
    public CustomerResponse getCustomerByEmail(String email) {
        Customer customer = customerRepository.findByEmailIgnoreCase(email)
                .orElseThrow(() -> CustomerNotFoundException.byEmail(email));
        return mapToResponse(customer);
    }

    // =========================================================
    // GET ALL
    // =========================================================
    @Override
    public List<CustomerResponse> getAllCustomers() {
        return customerRepository.findAll().stream()
                .map(this::mapToResponse).toList();
    }
    // =========================================================
    // GET ACTIVE CUSTOMERS
    // =========================================================

    @Override
    public List<CustomerResponse> getActiveCustomers() {
        return customerRepository.findByActiveTrue()
                .stream().map(this::mapToResponse).toList();
    }

    // =========================================================
    // SEARCH // =========================================================
    @Override
    public List<CustomerResponse> searchCustomers(String name) {
        return customerRepository
                .findByFirstNameContainingIgnoreCaseOrLastNameContainingIgnoreCase(name, name)
                .stream().map(this::mapToResponse).toList();
    }

    // =========================================================
    // UPDATE
    // =========================================================
    @Override
    @Transactional
    public CustomerResponse updateCustomer(UUID id, CustomerRequest request) {
        Customer customer = customerRepository.findById(id)
                .orElseThrow(() -> new CustomerNotFoundException(id));
        /*
         * * Customer number is generated by the system * and must never be changed
         * during an update.
         */
        validateUniqueEmailForUpdate(id, request.getEmail());
        mapRequestToEntity(request, customer);
        Customer updatedCustomer = customerRepository.save(customer);
        return mapToResponse(updatedCustomer);
    }

    // =========================================================
    // ACTIVATE
    // =========================================================
    @Override
    @Transactional
    public void activateCustomer(UUID id) {
        Customer customer = customerRepository.findById(id)
                .orElseThrow(() -> new CustomerNotFoundException(id));
        customer.setActive(true);
        customerRepository.save(customer);
    }

    // =========================================================
    // DEACTIVATE
    // =========================================================
    @Override
    @Transactional
    public void deactivateCustomer(UUID id) {
        Customer customer = customerRepository.findById(id)
                .orElseThrow(() -> new CustomerNotFoundException(id));
        customer.setActive(false);
        customerRepository.save(customer);
    }

    // =========================================================
    // DELETE
    // =========================================================

    @Override
    @Transactional
    public void deleteCustomer(UUID id) {
        Customer customer = customerRepository.findById(id)
                .orElseThrow(() -> new CustomerNotFoundException(id));
        customerRepository.delete(customer);
    }

    // =========================================================
    // VALIDATION
    // =========================================================
    private void validateUniqueCustomer(String email) {
        if (customerRepository.existsByEmailIgnoreCase(email)) {
            throw DuplicateCustomerException.byEmail(email);

        }
    }

    private void validateUniqueEmailForUpdate(UUID id, String email) {
        customerRepository.findByEmailIgnoreCase(email)
                .filter(customer -> !customer.getId().equals(id))
                .ifPresent(customer -> {
                    throw DuplicateCustomerException.byEmail(email);
                });
    }

    // =========================================================
    // MAPPING
    // =========================================================

    private void mapRequestToEntity(CustomerRequest request, Customer customer) {

        /*
         * * customerNumber intentionally not mapped. * It is generated by the system.
         */

        customer.setFirstName(request.getFirstName());
        customer.setLastName(request.getLastName());
        customer.setEmail(request.getEmail());
        customer.setPhone(request.getPhone());
        customer.setAddress(request.getAddress());
        customer.setCity(request.getCity());
        customer.setCountry(request.getCountry());
        customer.setActive(request.getActive());

    }

    private CustomerResponse mapToResponse(Customer customer) {
        CustomerResponse response = new CustomerResponse();
        response.setId(customer.getId());
        response.setCustomerNumber(customer.getCustomerNumber());
        response.setFirstName(customer.getFirstName());
        response.setLastName(customer.getLastName());
        response.setEmail(customer.getEmail());
        response.setPhone(customer.getPhone());
        response.setAddress(customer.getAddress());
        response.setCity(customer.getCity());
        response.setCountry(customer.getCountry());
        response.setActive(customer.getActive());
        response.setCreatedAt(customer.getCreatedAt());
        response.setUpdatedAt(customer.getUpdatedAt());

        return response;
    }
}